const Types = {
	SET_GAME_OVER: 'SET_GAME_OVER',
	SET_PLAYER_POS: 'SET_PLAYER_POS',
	SET_HEALTH: 'SET_HEALTH',
	SHUFFLE_GAME_GRID: 'SHUFFLE_GAME_GRID',
	SET_SCORE: 'SET_SCORE',
	RESET_GAME: 'RESET_GAME',
	SET_TO_FALSE: 'SET_TO_FALSE',
}

export default Types
